language: node_js
node_js:
  - "10.17.0"
dist: trusty
sudo: required
branches:
  only:
    - develop
    - master
before_install:
  - npm install -g @angular/cli
  - cd web; npm install
install:
  - npm run build-locale
  - npm install -g firebase-tools
  - firebase deploy --project pixblocksaddition --token "$FIREBASE_TOKEN"
