#stages:
#  - build
#  - name: deploy
#    if: branch = develop

jobs:
  include:
    - language: node_js
      node_js: "10.17.0"
      dist: trusty
      sudo: required
      branches:
        only:
          - fe-feature-128
      before_script:
        - npm install -g @angular/cli
        - cd web; npm install
      script:
        - npm run build-locale
        - npm install -g firebase-tools
        - firebase deploy --project pixblocksaddition --token "$FIREBASE_TOKEN"
    - language: csharp
        - dotnet: 2.2.402
          mono: none
      dist: bionic
      sudo: required
      branches:
        only:
          - fe-feature-128
      solution: PixBlocks_Addition.sln
      script:
        - dotnet restore
        - dotnet build


