using System;
using System.Collections.Generic;
using System.Text;

namespace PixBlocks_Addition.Tests.EndToEnd.Models
{
    public static class AuthorizationHeader
    {
        public static string Admin => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDIwODA0ZC01MWZkLTQ3ZjMtYjQ4MC05MWY4OGMzNjc1NGQiLCJ1bmlxdWVfbmFtZSI6IkFkbWluIiwianRpIjoiMDFmZWE4ZjktY2ExYS00YjlmLThmZWQtZjQzN2FiMzg2NDAxIiwicHJlbWl1bSI6IlRydWUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoyNTYxNDEyOTA3LCJpc3MiOiJwaXhibG9ja3NfYWRkaXRpb24ifQ.mca__YZ9IX_9AhZi-9dkPL0ngfJEdyBt_zioAxMsnGk";
    }
}
